import * as mongoose from 'mongoose';

export const FormSchema = new mongoose.Schema(
  {
    status: String,
    name: String,
    phone: String,
    email: String,
    cpf: String,
    address: String,
    event: String,
    eventKind: String,
    date: String,
    time: String,
    cerimonial: String,
    guestNumber: Number,
    locationEvent: String,
    locationCerimony: String,
    locationForniture: String,
    themeStyle: String,
    buffetKind: String,
    whatYouWant: String,
    colorsILike: String,
    colorsIDontLike: String,
    contractedServices: String,
    candyNumbers: Number,
    flowersIlike: String,
    flowersIDontLike: String,
    howDidYouFindUs: String,
    cantMissDecorations: String,
    othersInformations: String,
    inspirations: [{ path: String }],
    budget: String,
    contract: String,
  },
  { timestamps: true, collection: 'forms' },
);
